package com.tripoin.core.servlet;

/**
* @author <a href="ridla.fadilah@gmail.com">Ridla Fadilah</a>
*/
public class ApplicationContextConstant {

	public static final String CONTEXT_MENU_ROLE_ADMIN_WEB = "CONTEXT_MENU_ROLE_ADMIN_WEB";
	public static final String CONTEXT_MENU_ROLE_ADMIN_MOBILE = "CONTEXT_MENU_ROLE_ADMIN_MOBILE";
	public static final String CONTEXT_MENU_ROLE_SALESMAN_WEB = "CONTEXT_MENU_ROLE_SALESMAN_WEB";
	public static final String CONTEXT_MENU_ROLE_SALESMAN_MOBILE = "CONTEXT_MENU_ROLE_SALESMAN_MOBILE";
	public static final String CONTEXT_MENU_ROLE_AREASALESMANAGER_WEB = "CONTEXT_MENU_ROLE_AREASALESMANAGER_WEB";
	public static final String CONTEXT_MENU_ROLE_AREASALESMANAGER_MOBILE = "CONTEXT_MENU_ROLE_AREASALESMANAGER_MOBILE";
	public static final String CONTEXT_MENU_ROLE_NATIONALSALESMANAGER_WEB = "CONTEXT_MENU_ROLE_NATIONALSALESMANAGER_WEB";
	public static final String CONTEXT_MENU_ROLE_NATIONALSALESMANAGER_MOBILE = "CONTEXT_MENU_ROLE_NATIONALSALESMANAGER_MOBILE";
	
}
